### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by tim427**
Fixes 'non string unique_id'-error (introduced sinds 2024.5.0)
Added: Firmware version checks (first steps, still WIP)

### CODE REVIEW

**Review by emontnemery — COMMENTED** [review]
The changes in this PR will cause new new entities with a string unique_id to be created in addition to the existing lock entities with the incorrect unique_id.

To avoid that, update `async_setup_entry` to change unique_id of existing entity registry entries before the call to `hass.config_entries.async_forward_entry_setups`.

Find all entity registry entries for the config entry by calling `EntityRegistry.entities.get_entries_for_config_entry_id`, then iterate over the returned entries and call `EntityRegistry.async_update_entity(entity_id, new_unique_id=unique_id)` for each one.

**Comment by tim427** [comment]
> The changes in this PR will cause new new entities with a string unique_id to be created in addition to the existing lock entities with the incorrect unique_id.
> 
> To avoid that, update `async_setup_entry` to change unique_id of existing entity registry entries before the call to `hass.config_entries.async_forward_entry_setups`.
> 
> Find all entity registry entries for the config entry by calling `EntityRegistry.entities.get_entries_for_config_entry_id`, then iterate over the returned entries and call `EntityRegistry.async_update_entity(entity_id, new_unique_id=unique_id)` for each one.

I've just updated the Bold Component, and verified this method -> this works ;)

**Comment by yslaston** [comment]
> The changes in this PR will cause new new entities with a string unique_id to be created in addition to the existing lock entities with the incorrect unique_id.
> 
> To avoid that, update `async_setup_entry` to change unique_id of existing entity registry entries before the call to `hass.config_entries.async_forward_entry_setups`.
> 
> Find all entity registry entries for the config entry by calling `EntityRegistry.entities.get_entries_for_config_entry_id`, then iterate over the returned entries and call `EntityRegistry.async_update_entity(entity_id, new_unique_id=unique_id)` for each one.

Hi Erik, would it be possible to write few sentences of manual for non IT guys how to repair the issue with unique ID for bold integration?

**Comment by tim427** [comment]
@yslaston It's already fixed with commit #[54096f7](https://github.com/lwestenberg/homeassistant_bold/pull/29/commits/54096f749c5208939f25287dc7ee3be276d7c28e), which is in this pull request.

So for "non IT guys", it's just asking @lwestenberg for approval on this PR and waiting

**Comment by yslaston** [comment]
Thank you very much, will test it later on in the day.

**Pull request merged**
